name: Test and Build Artifact

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests and Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Run Gradle build
      - name: Run Gradle Build
        run: ./gradlew build --no-daemon

      # Run tests
      - name: Run Tests
        run: ./gradlew test --no-daemon
